#!/bin/bash

# shellcheck source=./util.sh disable=SC2155
function _dl_util_sh {
    local UTIL_VERSION="v2.2.5"
    local dir="$( dirname "$1" )"
    [ -f "${dir}/util.sh" ] || bash "${dir}/download-util.sh" "$UTIL_VERSION" || exit 1
    source "${dir}/util.sh"
}; _dl_util_sh "$0"

set -e

check "rustc"

msg "Compiling ./find_projects with rustc..."

rustc -C opt-level=3 "$@" \
    "${ROOT}/find_projects.rs"

msg "Done compiling, ready to use ./cdp.sh"
