#!/bin/bash
# Build script to compile `./find_projects.rs`.

# shellcheck source=./util.sh disable=SC2155
function _dl_util_sh {
    local UTIL_VERSION="v2.2.5"
    local dir="$( dirname "$1" )"
    [ -f "${dir}/util.sh" ] || bash "${dir}/download-util.sh" "$UTIL_VERSION" || exit 1
    source "${dir}/util.sh"
}; _dl_util_sh "$0"

set -e

check "rustc"

msg "Compiling $(clr "${CLR_CODE[@]}")./find_projects.rs$(clrrs)"

rustc -C opt-level=3 "$@" \
    "${ROOT}/find_projects.rs"

msg "Done compiling, ready to use $(clr "${CLR_CODE[@]}")./find_projects$(clrrs)"
